[
  "$mod, Q, exec, $terminal"
  "$mod, W, exec, $browser"
  "$mod, E, exec, $fileManager"
  "$mod, R, exec, $menu"
  "$mod, C, killactive"
  "$mod, F, togglefloating"
  "$mod SHIFT, F, fullscreen"
  "$mod, X, pseudo"
  "$mod, M, exit"
  "$mod, P, pseudo"
  "$mod, J, togglesplit"
  "$mod, left, movefocus, l"
  "$mod, right, movefocus, r"
  "$mod, up, movefocus, u"
  "$mod, down, movefocus, d"
  "$mod, 1, workspace, 1"
  "$mod, 2, workspace, 2"
  "$mod, 3, workspace, 3"
  "$mod, 4, workspace, 4"
  "$mod, 5, workspace, 5"
  "$mod, 6, workspace, 6"
  "$mod, 7, workspace, 7"
  "$mod, 8, workspace, 8"
  "$mod, 9, workspace, 9"
  "$mod, 0, workspace, 10"
  "$mod SHIFT, 1, movetoworkspace, 1"
  "$mod SHIFT, 2, movetoworkspace, 2"
  "$mod SHIFT, 3, movetoworkspace, 3"
  "$mod SHIFT, 4, movetoworkspace, 4"
  "$mod SHIFT, 5, movetoworkspace, 5"
  "$mod SHIFT, 6, movetoworkspace, 6"
  "$mod SHIFT, 7, movetoworkspace, 7"
  "$mod SHIFT, 8, movetoworkspace, 8"
  "$mod SHIFT, 9, movetoworkspace, 9"
  "$mod SHIFT, 0, movetoworkspace, 10"
  "$mod, Z, togglespecialworkspace, magic"
  "$mod SHIFT, Z, movetoworkspace, special:magic"
  "$mod, D, workspace, +1"
  "$mod, A, workspace, -1"
  "$mod SHIFT, D, movetoworkspace, +1"
  "$mod SHIFT, A, movetoworkspace, -1"
  "$mod, mouse_down, workspace, e+1"
  "$mod, mouse_up, workspace, e-1"
  "Shift, Alt_L, exec, hyprctl switchxkblayout at-translated-set-2-keyboard next"
  "Ctrl, Escape, exec, killall $panel || $panel"
  "$mod, V, exec, copyq toggle"
  "$mod, ESCAPE, exec, killall wlogout || wlogout"
  "$mod SHIFT, S, exec, sh -c 'grim -g \"$(slurp)\" - | satty -f -'"
  "Ctrl, Escape, exec, pkill waybar || waybar"
  ",XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"
  ",XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
  ",XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
  ",XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
  ",XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+"
  ",XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-"
  ", XF86AudioNext, exec, playerctl next"
  ", XF86AudioPause, exec, playerctl play-pause"
  ", XF86AudioPlay, exec, playerctl play-pause"
  ", XF86AudioPrev, exec, playerctl previous"
]
